$(document).ready(function(){
//Ä¿Â¼Ê÷
	$(".jsMlCont").find(".z_jian").click(function(){
		if(!$(this).parent().parent().nextAll().siblings("dd").is(":hidden")){
			$(this).parent().parent().nextAll().siblings("dd").hide();
			$(this).removeClass().addClass("z_jia");
		}
		else{
			$(this).parent().parent().nextAll().siblings("dd").show();
			$(this).addClass("z_jian").removeClass("z_jia");
		}
	});
//·­Ò³
	$(".i-r-link").hover(function(){
		$(this).children(".righg-icon").removeClass("nonea");
	},function(){
		$(this).children(".righg-icon").addClass("nonea");
	});

});