$(function(){
	//--
	$('.indexPart2_01').find('li:last').css('border','0px');
	//--
	$('.indexPart2_02').find('tr:even').find('td').css('background','#fffef6');
	//--
	var indexPart1_01Time;
	if($('.indexPart1_01').length>0){
		$('.indexPart1_01').find('.list').find('li:first').css('left',0);
		indexPart1_01Time=setInterval("indexPart1_01Fun()",5000);
		}	
	$('.indexPart1_01').find('span').each(function(i){
		$(this).click(function(){
			clearInterval(indexPart1_01Time);
			$('.indexPart1_01').find('span').removeClass('spanNow');
			$(this).addClass('spanNow');
			$('.indexPart1_01').find('.list1').find('li').hide();
			$('.indexPart1_01').find('.list').find('li').eq(indexPart1_01Now).animate({left: -522}, "slow",function(){
				$(this).css('left',522);
				});	
			indexPart1_01Now=i;
			$('.indexPart1_01').find('.list1').find('li').eq(indexPart1_01Now).show();
			$('.indexPart1_01').find('.list').find('li').eq(indexPart1_01Now).animate({left: 0}, "slow");		
			indexPart1_01Time=setInterval("indexPart1_01Fun()",5000);
			})
		})	
	//--
	$('.searchList').find('tr').find('td:last').css('border-right','0px');	
	$('.searchList').find('tr').find('th:last').css('border-right','0px');	
	$('.searchList').find('tr:odd').find('td').css('background','#f8f8f8');
	//--
	$('.searchFormA').click(function(){
		$('#searchForm').hide();
		})
	//--
	$('.classList').find('.list1:first').show();	
	$('.classList').find('.list').find('li').each(function(i){
		$(this).hover(
		   function(){
			   $('.classList').find('.list1').hide();
			   $('.classList').find('.list1').eq(i).show();
			   },
		   function(){}
		)
		})
	//--
	//$('.pageDiv:first').show();
	$('.sideNav').find('a').each(function(i){
		$(this).click(function(){
			$('.sideNav').find('a').removeClass('aNow');
			$(this).addClass('aNow');
			$('.pageDiv').hide();
			$('.pageDiv').eq(i).show();
			})
		})	
	//
	})